### ISSUE TITLE
Add a material design color palette

### ISSUE THREAD

**Issue by DawidKos** [DawidKos/Coloratura#3]
Link to material colors: https://www.materialpalette.com/colors
We define the new palette as a new class in the **colors.py** file using the Color function. Save colors in rgb format.

**Example:**
```py
class Pantone:
    """Pantone colors"""
    ILLUMINATING = Color('rgb', 245, 233, 77)  # 2021 - Color of the year
    ULTIMATE_GRAY = Color('rgb', 147, 149, 151)  # 2021 - Color of the year
    CLASSIC_BLUE = Color('rgb', 15, 76, 169)  # 2020 - Color of the year
    ...
```

**Comment by MariuszDrabik** [comment]
Hi! It should be all colours from colour palette from this material design site? Or just main colour? If You click for example on pink You flip up 13. colours form pink palette. So it should be main colour palette? Or all sub palettes? What about names?
PINK_100, PINK_200... ect? or something different?
